data:
  raw_path: "data/processed.cleveland.data"
  processed_path: "data/processed.csv"
  test_size: 0.2
  random_state: 42

model:
  name: "heart_disease_xgboost"
  n_estimators: 100
  max_depth: 3
  learning_rate: 0.1
  experiment_name: "heart_disease_prediction"

api:
  host: "0.0.0.0"
  port: 8000
  env: "dev"
