name: heart-disease-mlops
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10.12
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - jupyter=1.0.0

  - pip
  - pip:
    - mlflow==2.9.2
    - joblib==1.3.2
    - pyyaml==6.0.1
    - pytest==7.4.3
    - black==23.11.0
    - flake8==6.1.0
